Subindo back+front
bootcampnet2024/eShop pull request #41
Opened 2024-08-30 18:58 UTC by EduardoTCaetano

Correções de arquivos + CODEOWNERS e implementando os arquivos nesta nova branch

2024-09-02 10:21 UTC, bootcampnet2024 requested changes
Alguns ajustes necessários.

2024-09-02 10:21 UTC, bootcampnet2024 commented on src/Services/Basket/Basket.API/01-Services/BasketService.cs
> +        public void Add(CartItemDTO item, string userId)
Aqui vc precisa escolher a responsabilidade. Ou alterar de Add para AddOrUpdate ... e remover o Update abaixo ... ou a unica funcao dele é de Add. Manter os dois, em caso de Update, não sei qual chamar.

2024-09-02 10:21 UTC, bootcampnet2024 commented on src/Services/Basket/Basket.API/01-Services/IBasketService.cs
> +        void UpdateItem(CartItemDTO item, string userId);
Acredito que somente Update ja explica a funcao do método. Não é necessário UpdateItem()

2024-09-02 10:21 UTC, bootcampnet2024 commented on src/Services/Basket/Basket.API/02-Infrastructure/Migrations/20240809172406_AddNameDescriptionPriceToCartItem.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
Unificar todas as migrations. Há Migrations vazia. Antes do PR o ideal é unificar as alterações.

2024-09-02 10:21 UTC, bootcampnet2024 commented on src/Services/Basket/Basket.API/Basket.API.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
Esse pacote é necessário ? Não tenho certeza.

2024-09-02 10:21 UTC, bootcampnet2024 commented on src/Services/Basket/Basket.API/Controllers/BasketController.cs
> +        [HttpPost("add/{userId}")]
Um POST em /basket já induz a saber que é a inclusão de um item. Não precisa do add/

2024-09-02 10:21 UTC, bootcampnet2024 commented on src/Services/Basket/Basket.API/Controllers/BasketController.cs
> +        [HttpDelete("remove/{userId}/{productId}")]
Não há necessidade de remove/

2024-09-02 10:21 UTC, bootcampnet2024 commented on src/Services/Basket/Basket.API/Controllers/BasketController.cs
> +        [HttpPut("update")]
Não há necessidade de update .. só userId

2024-09-02 10:21 UTC, bootcampnet2024 commented on src/Services/Basket/Basket.API/Controllers/BasketController.cs
> +        [HttpGet("items/{userId}")]
Items não tem necessidade.

2024-09-02 10:21 UTC, bootcampnet2024 commented on tests/Basket.UnitTests/UnitTest1.cs
> +using Basket.API._01_Services;
O nome do arquivo não condiz com a classe

2024-09-02 13:36 UTC, EduardoTCaetano commented
Alterações enviadas

2024-09-09 10:52 UTC, bootcampnet2024 requested changes

2024-09-09 10:52 UTC, bootcampnet2024 commented on src/Services/Basket/Basket.API/appsettings.json
> +    "Default": "Server=ACER-DE-CAETANO\\SQLEXPRESS;Database=BasketDB;Trusted_Connection=True;Encrypt=True;TrustServerCertificate=True;"
Necessário conectar ao banco de dados que temos definido no docker compose.

2024-09-09 10:52 UTC, bootcampnet2024 commented on src/Web/eShop.Web/package-lock.json
Remover do PR. Não parece que houve atualizacao de pacotes de fato.

2024-09-12 10:32 UTC, bootcampnet2024 approved these changes

2024-09-12 10:33 UTC, merged