Web/global css
bootcampnet2024/eShop pull request #60
Opened 2024-10-08 05:12 UTC by aronbelodi

2024-10-08 11:42 UTC, bootcampnet2024 requested changes

2024-10-08 11:42 UTC, bootcampnet2024 commented on src/Web/eShop.Web/src/app/app.config.ts
> +<<<<<<< HEAD
problemas com rebase.

2024-10-10 10:24 UTC, bootcampnet2024 commented
So pra entender, os testes vão ser corrigidos nesse commit ou em outro ?

2024-10-10 17:19 UTC, aronbelodi commented
> So pra entender, os testes vão ser corrigidos nesse commit ou em outro ? https://github.com/bootcampnet2024/eShop/actions/runs/11259959954/job/31310115189?pr=60

Os testes serão corrigidos em um PR futuro focado para os testes do front

2024-10-10 17:30 UTC, bootcampnet2024 approved these changes

2024-10-10 17:30 UTC, merged